/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var Choir:String = "event:/Music/Gameplay_FinaleBattle/Drums/Choir";
    public static inline var LABS_Drums:String = "event:/Music/Gameplay_FinaleBattle/Drums/LABS_Drums";
    public static inline var Taiko_Drums:String = "event:/Music/Gameplay_FinaleBattle/Drums/Taiko_Drums";
    public static inline var _Finale_Music:String = "event:/Music/Gameplay_FinaleBattle/Drums/_Finale_Music";
}

class FmodSFX {
    public static inline var TestEvent:String = "event:/SFX/TestEvent";
}
